Sprint 10 - Nivell 1

Punt 1.
Importa com un DataFrame l'arxiu sprint10.xlsx. Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.

- Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.

- Mostra les primeres 10 files.

- Addicionalment, fes un print on comprovi que el DNI només té valors únics.

In [2]:
import pandas as pd
df = pd.read_excel('C:\\LLUIS\\Dropbox\\IT ACADEMY\\Sprint 10\\sprint10.xlsx',header=3,index_col=0)  
df = df.sort_values(by=['País d\'origen', 'Ciutat'],ascending=True)


# Comprovació d'unicitat del camp DNI
if df['DNI'].is_unique:
    print("El camp 'DNI' té valors únics.")
else:
    print("El camp 'DNI' conté valors duplicats.")
    # Mostrem quins DNIs estan duplicats
    duplicated_dnis = df[df['DNI'].duplicated(keep=False)].sort_values('DNI')
    print("DNIs duplicats trobats:")
    print(duplicated_dnis[['DNI']])

df.head(10)

El camp 'DNI' té valors únics.

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

Punt 2.
- Crea una columna que sigui el nom complet.

- Crea una columna si la persona és nascuda a Espanya o no.

- Posa el DNI com a índex del DataFrame (noms de files).

- Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.

- Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).

- Mostra tots els canvis que has realitzat en una sola taula.

In [3]:
# creació de la nova columna Nom_Complert
df.loc[(df["Nom"] != "") & (df["Cognoms"] != ""), "Nom_Complert"] = df["Nom"] + " " + df["Cognoms"]
df[["Nom", "Cognoms", "Nom_Complert"]].head(5)

       Nom              Cognoms             Nom_Complert
21     Mia    Schneider Fischer    Mia Schneider Fischer
154  Laura    Schneider Fischer  Laura Schneider Fischer
224    Lea  Schneider Schneider  Lea Schneider Schneider
278    Mia              Fischer              Mia Fischer
602  Jonas            Schneider          Jonas Schneider

In [4]:
# Crea una columna si la persona és nascuda a Espanya o no.
df['Nascut_a_Espanya'] = df['País d\'origen'].apply(lambda x: 'Sí' if x == 'Espanya' else 'No')
df[["Nom_Complert", "País d\'origen", "Nascut_a_Espanya"]].head(5)

                Nom_Complert País d'origen Nascut_a_Espanya
21     Mia Schneider Fischer      Alemanya               No
154  Laura Schneider Fischer      Alemanya               No
224  Lea Schneider Schneider      Alemanya               No
278              Mia Fischer      Alemanya               No
602          Jonas Schneider      Alemanya               No

In [5]:
# Posa el DNI com a índex del DataFrame (noms de files).
df.set_index('DNI', inplace=True)
df.head(5)

,Nom,Cognoms,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom_Complert,Nascut_a_Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No

In [6]:
# Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
df.rename(columns={'Dia de Naixement': 'Dia', 'Mes de Naixement': 'Mes', 'Any de Naixement': 'Any'}, inplace=True)
df.head(5)

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom_Complert,Nascut_a_Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No

In [7]:
# Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
df['Gènere'] = df['Gènere'].replace({'H': 'Home', 'D': 'Dona', 'A': 'Altres', 'NC': pd.NA})
#df['Gènere'].value_counts(dropna=False) 
df.head(10)

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom_Complert,Nascut_a_Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No
14773153R,Lea,Fischer,Alemanya,Berlín,9,9,1986,Dona,1.370 €,1.0,NaN,Grup A,Lea Fischer,No
23266650S,Lea,Müller,Alemanya,Hamburg,14,4,2003,Dona,1.314 €,NaN,1.0,Grup A,Lea Müller,No
83274277X,Anna,Müller,Alemanya,Hamburg,1,1,1987,Dona,2.464 €,NaN,1.0,Grup C,Anna Müller,No
60161784X,Laura,Schmidt Müller,Alemanya,Hamburg,15,6,1987,<NA>,2.035 €,1.0,NaN,Grup C,Laura Schmidt Müller,No
60982309S,Lukas,Müller Fischer,Alemanya,Hamburg,28,3,1971,Home,2.042 €,NaN,1.0,Grup B,Lukas Müller Fischer,No

Punt 3
- Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

In [8]:
# unta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".
def combinar_fills(row):
    if row['Fills'] == 1.0:
        return 'Sí'
    elif row['No Fills'] == 1.0:
        return 'No'    
    
   
df['Fills'] = df.apply(combinar_fills, axis=1)
df.drop(columns=['No Fills'], inplace=True)
df.head(10)

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom_Complert,Nascut_a_Espanya
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,Grup D,Jonas Schneider,No
14773153R,Lea,Fischer,Alemanya,Berlín,9,9,1986,Dona,1.370 €,Sí,Grup A,Lea Fischer,No
23266650S,Lea,Müller,Alemanya,Hamburg,14,4,2003,Dona,1.314 €,No,Grup A,Lea Müller,No
83274277X,Anna,Müller,Alemanya,Hamburg,1,1,1987,Dona,2.464 €,No,Grup C,Anna Müller,No
60161784X,Laura,Schmidt Müller,Alemanya,Hamburg,15,6,1987,<NA>,2.035 €,Sí,Grup C,Laura Schmidt Müller,No
60982309S,Lukas,Müller Fischer,Alemanya,Hamburg,28,3,1971,Home,2.042 €,No,Grup B,Lukas Müller Fischer,No

4.
- Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.

- Ordena la taula en funció del sou mig.

In [9]:
# Primer, netegem la columna 'Salari mensual' per convertir-la a numèrica
#df['Salari mensual'] = df['Salari mensual'].str.replace('€', '').str.replace('.', '').str.replace(',', '.').str.strip()
#df['Salari mensual'] = pd.to_numeric(df['Salari mensual'], errors='coerce')

 
"""
# Ara podem calcular la taula amb el sou mig per gènere
df_tauala_sou_mig = df.groupby("Gènere")["Salari numeric"].mean().round(2)

# Ara podem calcular la taula amb la media de sou per gènere
df_tauala_sou_media = df.groupby("Gènere")["Salari numeric"].median()

# Ara podem calcular la taula amb el mínim de sou per gènere
df_tauala_sou_minim = df.groupby("Gènere")["Salari numeric"].min()

# Ara podem calcular la taula amb el màxim de sou per gènere
df_tauala_sou_max = df.groupby("Gènere")["Salari numeric"].max()
df_taula_resum = pd.concat([df_tauala_sou_mig, df_tauala_sou_media, df_tauala_sou_minim, df_tauala_sou_max], axis=1, keys=['Sou Mig', 'Sou Media', 'Sou Mínim', 'Sou Màxim'])
df_taula_resum.head().sort_values(by='Sou Mig', ascending=False)
"""
#creo un camp nou de númeric per operar i així mantenir l'original
df['Salari numeric']= pd.to_numeric(df['Salari mensual'].str.replace('€', '').str.replace('.', '').str.replace(',', '.').str.strip(), errors='coerce') 

df_taula_resum = df.groupby("Gènere")["Salari numeric"].agg(['mean', 'median', 'min', 'max']).round(2)
df_taula_resum.rename(columns={'mean': 'Sou Mig', 'median': 'Sou Media', 'min': 'Sou Mínim', 'max': 'Sou Màxim'}, inplace=True)
df_taula_resum.head().sort_values(by='Sou Mig', ascending=False)

        Sou Mig  Sou Media  Sou Mínim  Sou Màxim
Gènere
Home    1643.25     1531.0        737       3356
Altres  1626.59     1545.0        703       3175
Dona    1469.44     1361.5        665       3021

5.
- Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).

- Afegeix-hi les mitjanes als marges de la taula.

- (EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors més elevats

In [24]:
import jinja2 as j2
# Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).

# Taula resum: salari mitjà per gènere (files) i país (columnes)
taula_resum_1 = df.pivot_table(
    values="Salari numeric",
    index="Gènere",
    columns="País d'origen",
    aggfunc="mean",
    margins=True,       # Afegeix files i columnes de mitjanes
    margins_name="Mitjana General"  # Nom de la fila/columna de totals
).round(2)

# Aplicar format condicional (de més clar a més fosc segons valor)
#taula_resum.style.background_gradient(cmap="Oranges")  # groc → taronja → vermell
taula_resum_1.style.format("{:.2f} €").background_gradient(cmap="Oranges")  # format d'euros

taula_resum_1

tabla_resum_2=pd.crosstab(
    index=df['Gènere'],
    columns=df['País d\'origen'],
    values=df['Salari numeric'],
    aggfunc='mean',
    margins=True,
    margins_name='Mitjana General'
)
tabla_resum_2.style.format("{:.2f} €").background_gradient(cmap="Oranges")  # format d'euros

6.
- Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any. Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.

- Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [11]:
from datetime import date, datetime

def calcular_edat(data_naixement):
    """
    Rep una data de naixement (datetime.date o cadena) i retorna l'edat en anys.
    """
    # Si la data ve com a cadena, la convertim a objecte date
    if isinstance(data_naixement, str):
        try:
            data_naixement = datetime.strptime(data_naixement, "%Y-%m-%d").date()
        except ValueError:
            data_naixement = datetime.strptime(data_naixement, "%d/%m/%Y").date()

    avui = date.today()
    edat = avui.year - data_naixement.year - ((avui.month, avui.day) < (data_naixement.month, data_naixement.day))
    return edat


# Crear un diccionari amb les parts de la data
dates = {'year': df['Any'], 'month': df['Mes'], 'day': df['Dia']}

# Convertir a dates vàlides (els errors es converteixen a NaT)
df['naixament'] = pd.to_datetime(dates, errors='coerce')

# Calcular l'edat i crear la nova columna 'Edat'
df['Edat'] = df['naixament'].apply(calcular_edat)
df.head(10)

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom_Complert,Nascut_a_Espanya,Salari numeric,naixament,Edat
DNI,,,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,Grup A,Mia Schneider Fischer,No,951,1976-10-22,49
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,Grup B,Laura Schneider Fischer,No,1769,1958-02-02,67
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,Grup B,Lea Schneider Schneider,No,2013,2005-10-23,20
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,Grup B,Mia Fischer,No,1557,1950-08-11,75
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,Grup D,Jonas Schneider,No,2754,1985-11-22,39
14773153R,Lea,Fischer,Alemanya,Berlín,9,9,1986,Dona,1.370 €,Sí,Grup A,Lea Fischer,No,1370,1986-09-09,39
23266650S,Lea,Müller,Alemanya,Hamburg,14,4,2003,Dona,1.314 €,No,Grup A,Lea Müller,No,1314,2003-04-14,22
83274277X,Anna,Müller,Alemanya,Hamburg,1,1,1987,Dona,2.464 €,No,Grup C,Anna Müller,No,2464,1987-01-01,38
60161784X,Laura,Schmidt Müller,Alemanya,Hamburg,15,6,1987,<NA>,2.035 €,Sí,Grup C,Laura Schmidt Müller,No,2035,1987-06-15,38
60982309S,Lukas,Müller Fischer,Alemanya,Hamburg,28,3,1971,Home,2.042 €,No,Grup B,Lukas Müller Fischer,No,2042,1971-03-28,54

Nivell 2

1.
- Utilitzant el següent DataFrame, adjunta la columna "Increment" al dataframe del nivell anterior.

- Actualitza la columna salari en funció dels percentatges que s'adjunten. No modifiquis manualment els increments, escriu codi Python per fer les conversions necessàries.

df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":

["5%","3,5%","2%","8%"]})

In [12]:
def calcular_increment(salari, increment):
    """
    Rep un salari (float) i un increment (cadena amb percentatge, ex. '5%' o '3,5%') i retorna el nou salari amb l'increment aplicat.
    """
    if pd.isna(salari) or pd.isna(increment):
        return salari  # Si algun valor és NaN, retornem el salari original

    # Convertim l'increment a float
    increment = increment.replace('%', '').replace(',', '.').strip()
    try:
        increment_float = float(increment) / 100.0
    except ValueError:
        return salari  # Si no es pot convertir, retornem el salari original

    nou_salari = salari * (1 + increment_float)
    return round(nou_salari, 2)

df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":["5%","3,5%","2%","8%"]})

df['increment'] = df['Grup Professional'].map(df_increment.set_index('Grup')['Increment'])
df['Salari actualitzat'] = df.apply(lambda row: calcular_increment(row['Salari numeric'], row['increment']), axis=1)
df[['Nom_Complert', 'Grup Professional', 'Salari mensual', 'Salari numeric', 'increment', 'Salari actualitzat']].head(10)

,Nom_Complert,Grup Professional,Salari mensual,Salari numeric,increment,Salari actualitzat
DNI,,,,,,
28973553Z,Mia Schneider Fischer,Grup A,951 €,951,5%,998.55
37399141L,Laura Schneider Fischer,Grup B,1.769 €,1769,"3,5%",1830.91
37368317L,Lea Schneider Schneider,Grup B,2.013 €,2013,"3,5%",2083.45
21390098Z,Mia Fischer,Grup B,1.557 €,1557,"3,5%",1611.49
44060014R,Jonas Schneider,Grup D,2.754 €,2754,8%,2974.32
14773153R,Lea Fischer,Grup A,1.370 €,1370,5%,1438.50
23266650S,Lea Müller,Grup A,1.314 €,1314,5%,1379.70
83274277X,Anna Müller,Grup C,2.464 €,2464,2%,2513.28
60161784X,Laura Schmidt Müller,Grup C,2.035 €,2035,2%,2075.70
60982309S,Lukas Müller Fischer,Grup B,2.042 €,2042,"3,5%",2113.47

2.
Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.

Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...

Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.

In [13]:
for grup in df['Grup Professional'].unique():
    df_grup = df[df['Grup Professional'] == grup]
    nom_fitxer = f'dades_{grup.replace(" ", "")}.csv'  # o .xlsx si prefereixes aquest format
    df_grup.to_csv(nom_fitxer, index=False)
    df_grup.to_excel(nom_fitxer.replace('.csv', '.xlsx'), index=False)
    print(f'Fitxer creat: {nom_fitxer}')

# Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, 
# quin és el seu sou mig i quina és la seva edat mediana.
df_resum_grup = df.groupby('Grup Professional').agg(
    Num_Treballadors=('Nom', 'count'),
    Sou_Mig=('Salari numeric', 'mean'),
    Edat_Mediana=('Edat', 'median')
).round(2)
df_resum_grup.to_csv('resum_grup_professional.csv')
df_resum_grup.to_excel('resum_grup_professional.xlsx')
df_resum_grup

Fitxer creat: dades_GrupA.csv
Fitxer creat: dades_GrupB.csv
Fitxer creat: dades_GrupD.csv
Fitxer creat: dades_GrupC.csv

                   Num_Treballadors  Sou_Mig  Edat_Mediana
Grup Professional
Grup A                          490  1155.55          50.0
Grup B                          318  1666.23          47.0
Grup C                          137  2244.31          51.0
Grup D                           55  2871.13          43.0